name: pdf_reader_pro
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0
  shared_preferences: ^2.2.2
  syncfusion_flutter_pdfviewer: ^26.2.10
  firebase_core: ^3.5.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.5

flutter:
  uses-material-design: true
